# Generated by Django 5.0 on 2024-02-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('habits_done', models.IntegerField()),
                ('total_day_score', models.IntegerField()),
            ],
        ),
    ]
