# Generated by Django 5.0.2 on 2024-03-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_remove_response_request_habitrequest_delete_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitrequest',
            name='number_of_habits',
            field=models.IntegerField(default=0),
        ),
    ]
