# Generated by Django 5.0.3 on 2024-03-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_remove_response_request_habitrequest_responserequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitrequest',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Reviewed'),
        ),
    ]
