# Generated by Django 5.0.2 on 2024-03-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_habitrequest_number_of_habits'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitrequest',
            name='acknowledged',
            field=models.BooleanField(default=False, verbose_name='Acknowledged by User'),
        ),
    ]
