# Generated by Django 5.0.2 on 2024-03-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0007_userseedaward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSeedAward',
        ),
    ]
