# Generated by Django 5.0.2 on 2024-02-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
