# Generated by Django 5.0 on 2024-02-24 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walk', models.BooleanField(default=False)),
                ('plastic', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('water_bottle', models.BooleanField(default=False)),
                ('utensils', models.BooleanField(default=False)),
                ('short_trips', models.BooleanField(default=False)),
                ('plant_based_meals', models.BooleanField(default=False)),
                ('unplug_electronics', models.BooleanField(default=False)),
                ('natural_light', models.BooleanField(default=False)),
                ('community_cleanups', models.BooleanField(default=False)),
                ('reduce_food_waste', models.BooleanField(default=False)),
                ('public_transportation', models.BooleanField(default=False)),
                ('turn_off_lights', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('streak_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
