# Generated by Django 5.0 on 2024-03-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantedSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_type', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='usergarden',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='usergarden',
            name='user',
        ),
        migrations.DeleteModel(
            name='SeedInventory',
        ),
        migrations.DeleteModel(
            name='UserGarden',
        ),
    ]
