# Generated by Django 5.0.3 on 2024-03-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergarden',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='usergarden',
            name='user',
        ),
        migrations.DeleteModel(
            name='SeedInventory',
        ),
        migrations.DeleteModel(
            name='UserGarden',
        ),
    ]
