# Generated by Django 5.0 on 2024-03-15 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_plantedseed_remove_usergarden_seed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantedseed',
            name='planted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
