# Generated by Django 5.0 on 2024-03-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_plantedseed_planted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantedseed',
            name='planted_by',
        ),
    ]
