# Generated by Django 5.0.1 on 2024-03-20 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_plantedseed_user'),
        ('garden', '0006_userseed'),
    ]

    operations = [
    ]
