# Generated by Django 5.0.2 on 2024-03-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0008_alter_userseed_user'),
    ]

    operations = [
    ]
