# Generated by Django 5.0.2 on 2024-03-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_plantedseed_user'),
        ('garden', '0009_fix_null_userseeds'),
    ]

    operations = [
    ]
