# Generated by Django 5.0.1 on 2024-03-21 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_merge_0006_plantedseed_user_0006_userseed'),
        ('garden', '0010_merge_0006_plantedseed_user_0009_fix_null_userseeds'),
    ]

    operations = [
    ]
